### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [DRot88/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by DRot88** [comment]
Hi Ken,

I updated my HTML to include the mobile meta tag (it was pushed to github as well as heroku). I did notice that the modal gets cut off on mobile as well though.

**Comment by kenmazaika** [comment]
Solid work getting the mobile tag in there.

Getting the modal to be perfect is actually a bit of work.  Realistically it would make sense to only use the modal in non-mobile views, otherwise go to an entirely different page, but that's quite a bit of work.

Keep up the good work coding, Daniel!
